
#####
# Step 1 - ModelBuilder to Python Script
#####

# Task 1 - Using the provided model - Step_1_toolbox.zip, export the Model to a python script and paste below.
# In Model Builder, go to the menu item Model > Export > To Python Script.

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-03-12 12:31:57
"""
import arcpy

def Model():  # Find Areas Suitable for Development

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Roads = "RI_Roads"
    Places = "Places"
    State_Boundary = "State_Boundary_1997"

    # Process: Buffer roads (Buffer) (analysis)
    Buffered_Roads = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\RI_Roads_Buffer"
    arcpy.analysis.Buffer(in_features=Roads, out_feature_class=Buffered_Roads, buffer_distance_or_field="10 Miles", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

    # Process: Buffer places (Buffer) (analysis)
    Buffered_Places = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\Places_Buffer"
    arcpy.analysis.Buffer(in_features=Places, out_feature_class=Buffered_Places, buffer_distance_or_field="10 Miles", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

    # Process: Buffered data intersected (Intersect) (analysis)
    Buffered_data_intersected_output = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\RI_Roads_Buffer_Intersect"
    arcpy.analysis.Intersect(in_features=[[Buffered_Roads, ""], [Buffered_Places, ""]], out_feature_class=Buffered_data_intersected_output, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

    # Process: Clip (Clip) (analysis)
    Suitable_Areas_for_Development = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\State_Boundary_1997_Clip"
    arcpy.analysis.Clip(in_features=Buffered_data_intersected_output, clip_features=State_Boundary, out_feature_class=Suitable_Areas_for_Development, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\andrewdavies\Documents\ArcGIS\Projects\MyProject3\MyProject3.gdb", workspace=r"C:\Users\andrewdavies\Documents\ArcGIS\Projects\MyProject3\MyProject3.gdb"):
        Model()