
#####
# Step 1 - ModelBuilder to Python Script
#####

# Task 1 - Using the provided model - Step_1_toolbox.zip, export the Model to a python script and paste below.
# In Model Builder, go to the menu item Model > Export > To Python Script.

# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2019-02-27 19:57:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Roads = "RI_Roads"
Buffered_Roads = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\RI_Roads_Buffer"
Places = "Places"
Buffered_Places = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\Places_Buffer"
Buffered_data_intersected_output = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\RI_Roads_Buffer_Intersect"
State_Boundary = "State_Boundary_1997"
Suitable_Areas_for_Development = "C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\State_Boundary_1997_Clip"

# Process: Buffer roads
arcpy.Buffer_analysis(Roads, Buffered_Roads, "10 Miles", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer places
arcpy.Buffer_analysis(Places, Buffered_Places, "10 Miles", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffered data intersected
arcpy.Intersect_analysis("C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\RI_Roads_Buffer #;C:\\Users\\andrewdavies\\Documents\\ArcGIS\\Default.gdb\\Places_Buffer #",
                         Buffered_data_intersected_output, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Buffered_data_intersected_output, State_Boundary, Suitable_Areas_for_Development, "")


# Task 2 - Edit the inputs to run the code using the data in Step_1_data.zip, some starter code has been provided.
Roads = "RI_Roads"
Places = "Places"
State_Boundary = "State_Boundary_1997"

